// Sample project data
export const pinnedProjects = [
  {
    id: "gis-1",
    title: "Urban Growth Prediction",
    description: "GIS-based model to predict urban expansion patterns using historical data.",
    category: "GIS",
    image: "/placeholder.svg?height=192&width=384",
    tags: ["Spatial Analysis", "Remote Sensing", "Urban Planning"],
    demoUrl: "#",
    githubUrl: "#",
  },
  {
    id: "ml-1",
    title: "Climate Change Prediction",
    description: "Machine learning model to predict climate patterns based on historical data.",
    category: "Machine Learning",
    image: "/placeholder.svg?height=192&width=384",
    tags: ["Regression", "Time Series", "Data Visualization"],
    demoUrl: "#",
    githubUrl: "#",
  },
  {
    id: "ai-1",
    title: "Natural Language Processor",
    description: "AI system for processing and analyzing natural language text data.",
    category: "AI",
    image: "/placeholder.svg?height=192&width=384",
    tags: ["NLP", "Text Mining", "Sentiment Analysis"],
    demoUrl: "#",
    githubUrl: "#",
  },
  {
    id: "nn-1",
    title: "Image Classification System",
    description: "Neural network for classifying satellite imagery for land use analysis.",
    category: "Neural Network",
    image: "/placeholder.svg?height=192&width=384",
    tags: ["CNN", "Computer Vision", "Satellite Imagery"],
    demoUrl: "#",
    githubUrl: "#",
  },
]

// Extended project list for portfolio page
export const allProjects = [
  ...pinnedProjects,
  {
    id: "gis-2",
    title: "Flood Risk Assessment",
    description: "GIS analysis to identify areas at risk of flooding based on topography and rainfall data.",
    category: "GIS",
    image: "/placeholder.svg?height=192&width=384",
    tags: ["Hydrological Modeling", "Risk Assessment", "Spatial Analysis"],
    demoUrl: "#",
    githubUrl: "#",
  },
  {
    id: "gis-3",
    title: "Transportation Network Analysis",
    description: "Analysis of urban transportation networks to optimize routes and reduce congestion.",
    category: "GIS",
    image: "/placeholder.svg?height=192&width=384",
    tags: ["Network Analysis", "Urban Planning", "Optimization"],
    demoUrl: "#",
    githubUrl: "#",
  },
  {
    id: "ml-2",
    title: "Crop Yield Prediction",
    description: "Machine learning model to predict agricultural yields based on environmental factors.",
    category: "Machine Learning",
    image: "/placeholder.svg?height=192&width=384",
    tags: ["Random Forest", "Agricultural Data", "Predictive Modeling"],
    demoUrl: "#",
    githubUrl: "#",
  },
  {
    id: "ml-3",
    title: "Customer Segmentation",
    description: "Clustering algorithm to segment customers based on purchasing behavior.",
    category: "Machine Learning",
    image: "/placeholder.svg?height=192&width=384",
    tags: ["Clustering", "K-Means", "Market Analysis"],
    demoUrl: "#",
    githubUrl: "#",
  },
  {
    id: "ai-2",
    title: "Recommendation System",
    description: "AI-powered recommendation system for personalized content delivery.",
    category: "AI",
    image: "/placeholder.svg?height=192&width=384",
    tags: ["Collaborative Filtering", "Content-Based Filtering", "User Modeling"],
    demoUrl: "#",
    githubUrl: "#",
  },
  {
    id: "ai-3",
    title: "Chatbot Assistant",
    description: "Intelligent chatbot for customer service and information retrieval.",
    category: "AI",
    image: "/placeholder.svg?height=192&width=384",
    tags: ["Natural Language Processing", "Dialog Systems", "Intent Recognition"],
    demoUrl: "#",
    githubUrl: "#",
  },
  {
    id: "nn-2",
    title: "Object Detection System",
    description: "Neural network for detecting and classifying objects in images and video.",
    category: "Neural Network",
    image: "/placeholder.svg?height=192&width=384",
    tags: ["YOLO", "Computer Vision", "Real-time Detection"],
    demoUrl: "#",
    githubUrl: "#",
  },
  {
    id: "nn-3",
    title: "Time Series Forecasting",
    description: "Neural network for predicting future values in time series data.",
    category: "Neural Network",
    image: "/placeholder.svg?height=192&width=384",
    tags: ["LSTM", "RNN", "Forecasting"],
    demoUrl: "#",
    githubUrl: "#",
  },
]
